language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
install:
    - pip install -r requirements.txt
script:
    - ./run-code-analysis.sh
after_success:
  - coveralls
notifications:
  email: false
